# myLevs: Number of levels of Feeling: 3 or 5 or 0 (leave original #levels unaltered)
myLevs <- 0

# Hole for pie plots in Descriptive: 0: pie; >=0: donut
holepie <- 0.5

# Number of clusters to search in each single Triad
Nclust <- 0 # (0 means no clustering)
# Number of (largest) clusters to plot in each single Triad
Nclustplot <- 3
# Confidence level of ellipses in clusters: 0.05: 2 sdv; 0.32: 1sdv
alphaclust <- 0.05

# Number of clusters to search in all joint Triads
Nclustall <- 20 # (0 means no clustering)
# Number of (largest) clusters to plot in all joint Triads
Nclustallplot <- Nclustall

Ncountry <- 6
Country <- array(list(), Ncountry)


# Country 6: Yemen
Country[[6]] <- list(country = "Yemen", countrycode = "YEM",
                     latmin = 12, latmax = 19, lonmin = 42, lonmax = 55,
                     variables_to_transalte = c("Your.experience",
                                                "StoryTitle",
                                                "Q4.Who.influenced..Other",
                                                "Q5.Story.involves..Other",
                                                "Q6.WhoImpacted..Other",
                                                "DQ3.Employment.status..Other",
                                                "DQ7.Which.group.identify.with..Other"),
                     var_age = "Age",
                     var_gender = "Gender",
                     var_employment = "Employment",
                     var_education = "Education",
                     var_live = "Live",
                     var_marital = "Marital",
                     var_group = list(V="DQ7.Which.group.identify.with",
                                      Vname="Group",
                                      VV=c("internally\ndisplaced persons",
                                           "refugee",
                                           "resident/host",
                                           "marginalised")),
                     var_multiple = array(list(
                       list(T="Q5 Story involves",
                            TT=c("Politics","Trust","Business trade","Environment","Corruption","Justice",
                                 "Poverty","International relations","Respect tolerance","Human rights",
                                 "Education","Violence"))
                     )),
                     var_triads = array(list(
                       list(T="T1 What prevented things",
                            TT=c("Lack of\nopportunities",
                                 "Lack of\nrelevant skills",
                                 "Lack of\nresources")),
                       list(T="T2 Decisions based on",
                            TT=c("Personal judgement/\nexperience",
                                 "Information/advice/\nexperience of others",
                                 "Resources/\nincome")),
                       list(T="T3 What people pursued",
                            TT=c("Survival",
                                 "Power/status",
                                 "Wealth")),
                       list(T="T4 Why people took action",
                            TT=c("They went with\nthe flow",
                                 "They made up\ntheir own minds",
                                 "They followed\nothers orders")),
                       list(T="T5 What underlined approach",
                            TT=c("Practical issues",
                                 "Moral obligations/\nsocial norms",
                                 "Legality/\nlegislation")),
                       list(T="T6 Attitude of people was",
                            TT=c("Some people worth\nmore than others",
                                 "Everyone should be\ntreated the same",
                                 "Diversity is good")),
                       list(T="T7 Lesson applies to",
                            TT=c("Past",
                                 "Present",
                                 "Future")),
                       list(T="T8 Attitudes revealed were",
                            TT=c("Keeping\ntradition",
                                 "Wanting things\nto change",
                                 "Just trying\nto survive")),
                       list(T="T9 People had",
                            TT=c("A sense of\nbelonging",
                                 "Choices",
                                 "Confidence"))
                     ))
)
# 
# # Country 1: Kirghizistan
Country[[1]] <- list(country = "Kyrgyzstan", countrycode = "KGZ",
                     latmin = 39, latmax = 43.5, lonmin = 72, lonmax = 80.5,
                     variables_to_transalte = c("Your.experience",
                                                "StoryTitle",
                                                "Q4.Who.influenced..Other",
                                                "Q5.Story.involves..Other",
                                                "Q6.WhoImpacted..Other"),
                     var_age = "Age",
                     var_gender = "Gender",
                     var_employment = "Employment",
                     var_education = "Education",
                     var_live = "Live",
                     var_marital = "Marital",
                     var_group = list(V="DQ7.Which.group.identify.with",
                                      Vname="Group",
                                      VV=c("internally displaced persons",
                                           "refugee",
                                           "resident/host",
                                           "marginalised")),
                     var_triads = array(list(
                       list(T="T1 People were",
                            TT=c("resourceful\npersistent",
                                 "future\nfocused",
                                 "resilient/\nadaptable")),
                       list(T="T2 People affected by",
                            TT=c("beliefs/traditional\nvalues",
                                 "information",
                                 "actions/events")),
                       list(T="T3  What made things happen",
                            TT=c("Government/\ninstitutions",
                                 "Communities/\nyour networks",
                                 "Specific individuals")),
                       list(T="T4 Lesson applies to",
                            TT=c("Past",
                                 "Present",
                                 "Future")),
                       list(T="T5 What people pursued",
                            TT=c("Food security",
                                 "personal/\nproperty security",
                                 "community/\nfamily security")),
                       list(T="T6 What shaped events",
                            TT=c("Trust",
                                 "Understanding",
                                 "Personal efforts")),
                       list(T="T7 What people value",
                            TT=c("Ability to\nafford things",
                                 "Ability to\naffect decisions",
                                 "Ability to\nmake choices")),
                       list(T="T8 Government was",
                            TT=c("stable",
                                 "fair/unbiased",
                                 "accessible")),
                       list(T="T9 People had",
                            TT=c("A sense of\nbelonging",
                                 "Choices",
                                 "Confidence"))
                     ))
)
# Country 2: Moldova
Country[[2]] <- list(country = "Moldova", countrycode = "MDA",
                     latmin = 28, latmax = 48.5, lonmin = 26.5, lonmax = 30.5,
                     variables_to_transalte = c("Your.experience",
                                                "StoryTitle",
                                                "Q4.Who.influenced..Other",
                                                "Q5.Story.involves..Other",
                                                "Q6.WhoImpacted..Other"),
                     var_age = "Age",
                     var_gender = "Gender",
                     var_employment = "Employment",
                     var_education = "Education",
                     var_live = "Live",
                     var_marital = "Marital",
                     var_group = list(V="DQ7.Which.group.identify.with",
                                      Vname="Group",
                                      VV=c("internally displaced persons",
                                           "refugee",
                                           "resident/host",
                                           "marginalised")),
                     var_triads = array(list(
                       list(T="T1 People were",
                            TT=c("resourceful\npersistent",
                                 "future\nfocused",
                                 "resilient/\nadaptable")),
                       list(T="T2 People affected by",
                            TT=c("beliefs/traditional\nvalues",
                                 "information",
                                 "actions/events")),
                       list(T="T3  What made things happen",
                            TT=c("Government/\ninstitutions",
                                 "Communities/\nyour networks",
                                 "Specific individuals")),
                       list(T="T4 Lesson applies to",
                            TT=c("Past",
                                 "Present",
                                 "Future")),
                       list(T="T5 What people pursued",
                            TT=c("Food security",
                                 "personal/\nproperty security",
                                 "community/\nfamily security")),
                       list(T="T6 What shaped events",
                            TT=c("Trust",
                                 "Understanding",
                                 "Personal efforts")),
                       list(T="T7 What people value",
                            TT=c("Ability to\nafford things",
                                 "Ability to\naffect decisions",
                                 "Ability to\nmake choices")),
                       list(T="T8 Government was",
                            TT=c("stable",
                                 "fair/unbiased",
                                 "accessible")),
                       list(T="T9 People had",
                            TT=c("A sense of\nbelonging",
                                 "Choices",
                                 "Confidence"))
                     ))
)
# Country 5: Tajikistan
Country[[5]] <- list(country = "Tajikistan", countrycode = "TJK",
                     latmin = 36.5, latmax = 41.5, lonmin = 67, lonmax = 75.5,
                     variables_to_transalte = c("Describe.your.example.here",
                                                "lackingKnowledgeOther",
                                                "Q5.In.your.example.what.knowledge.were.people.lacking.most..select.up.to.2.._N.A",
                                                "ImprovedYourSituationOther",
                                                "sectorWomanEngagedInOther",
                                                "MCQ7_Others",
                                                "C4.Other.notes"),
                     var_age = "Age",
                     var_gender = "Gender",
                     var_employment = "Employment",
                     var_education = "R3.Highest.level.of.education.achieved",
                     var_live = "Live",
                     var_marital = "Marital",
                     var_group = list(V="DQ7.Which.group.identify.with",
                                      Vname="Group",
                                      VV=c("internally displaced persons",
                                           "refugee",
                                           "resident/host",
                                           "marginalised")),
                     var_triads = array(list(
                       list(T="T1 People engaged in entrepreneurship because they",
                            TT=c("needed to survive",
                                 "wanted something\nbetter",
                                 "had a business\nidea/skills")),
                       list(T="T2 What helped things?",
                            TT=c("Training/educational\nprogrammes",
                                 "Access to\nmarkets",
                                 "informal networks")),
                       list(T="T3 What prevented things from happening?",
                            TT=c("Lack of\nknowledge/skills",
                                 "Lack of state/social\nsupport",
                                 "lack of family/society\nsupport")),
                       list(T="T4 How did people learn about new things and opportunities?",
                            TT=c("State programmes",
                                 "Family/friends/\nself-help group",
                                 "Business associations/\norganisations/NGOs")),
                       list(T="T5 What mattered?",
                            TT=c("What was\nproduced/offered",
                                 "How products/services\nwere produced",
                                 "Access to markets")),
                       list(T="T6 Information about starting up and running a business was",
                            TT=c("not accessible",
                                 "of bad quality",
                                 "not relevant"))
                     ))
)
# Country 4: Serbia
Country[[4]] <- list(country = "Serbia", countrycode = "SRB",
                     latmin = 42, latmax = 46.5, lonmin = 18.5, lonmax = 23,
                     variables_to_transalte = c("Your.experience",
                                                "StoryTitle",
                                                "Q4.Who.influenced..Other",
                                                "Q5.Story.involves..Other",
                                                "Q6.WhoImpacted..Other"),
                     var_age = "Age",
                     var_gender = "Gender",
                     var_employment = "Employment",
                     var_education = "Education",
                     var_live = "Live",
                     var_marital = "Marital",
                     var_group = list(V="DQ7.Which.group.identify.with",
                                      Vname="Group",
                                      VV=c("internally displaced persons",
                                           "refugee",
                                           "resident/host",
                                           "marginalised")),
                     var_triads = array(list(
                       list(T="T1 People were",
                            TT=c("resourceful\npersistent",
                                 "future\nfocused",
                                 "resilient/\nadaptable")),
                       list(T="T2 People affected by",
                            TT=c("beliefs/traditional\nvalues",
                                 "information",
                                 "actions/events")),
                       list(T="T3  What made things happen",
                            TT=c("Government/\ninstitutions",
                                 "Communities/\nyour networks",
                                 "Specific individuals")),
                       list(T="T4 Lesson applies to",
                            TT=c("Past",
                                 "Present",
                                 "Future")),
                       list(T="T5 What people pursued",
                            TT=c("Food security",
                                 "personal/\nproperty security",
                                 "community/\nfamily security")),
                       list(T="T6 What shaped events",
                            TT=c("Trust",
                                 "Understanding",
                                 "Personal efforts")),
                       list(T="T7 What people value",
                            TT=c("Ability to\nafford things",
                                 "Ability to\naffect decisions",
                                 "Ability to\nmake choices")),
                       list(T="T8 Government was",
                            TT=c("stable",
                                 "fair/unbiased",
                                 "accessible")),
                       list(T="T9 People had",
                            TT=c("A sense of\nbelonging",
                                 "Choices",
                                 "Confidence"))
                     ))
)
# Country 3 : Unicef
Country[[3]] <- list(country = "Kyrgyzstan Unicef", countrycode = "UNI",
                     latmin = 39, latmax = 43.5, lonmin = 72, lonmax = 80.5,
                     variables_to_transalte = c("Your.experience",
                                                "StoryTitle",
                                                "Q4.Who.influenced..Other",
                                                "Q5.Story.involves..Other",
                                                "Q6.WhoImpacted..Other"),
                     var_age = "Age",
                     var_gender = "Gender",
                     var_employment = "Employment",
                     var_education = "Education",
                     var_live = "Live",
                     var_marital = "Marital",
                     var_group = list(V="DQ7.Which.group.identify.with",
                                      Vname="Group",
                                      VV=c("internally displaced persons",
                                           "refugee",
                                           "resident/host",
                                           "marginalised")),
                     var_triads = array(list(
                       list(T="T1 People were",
                            TT=c("resourceful\npersistent",
                                 "future\nfocused",
                                 "resilient/\nadaptable")),
                       list(T="T2 People affected by",
                            TT=c("beliefs/traditional\nvalues",
                                 "information",
                                 "actions/events")),
                       list(T="T3  What made things happen",
                            TT=c("Government/\ninstitutions",
                                 "Communities/\nyour networks",
                                 "Specific individuals")),
                       list(T="T4 Lesson applies to",
                            TT=c("Past",
                                 "Present",
                                 "Future")),
                       list(T="T5 What people pursued",
                            TT=c("Food security",
                                 "personal/\nproperty security",
                                 "community/\nfamily security")),
                       list(T="T6 What shaped events",
                            TT=c("Trust",
                                 "Understanding",
                                 "Personal efforts")),
                       list(T="T7 What people value",
                            TT=c("Ability to\nafford things",
                                 "Ability to\naffect decisions",
                                 "Ability to\nmake choices")),
                       list(T="T8 Government was",
                            TT=c("Stable",
                                 "Fair/unbiased",
                                 "Accessible")),
                       list(T="T9 People had",
                            TT=c("A sense of\nbelonging",
                                 "Choices",
                                 "Confidence")),
                       list(T="T10 People your age",
                            TT=c("Coping with\ndifficult challenges",
                                 "Stopping\nsomething happening",
                                 "Improving the\nsituation")),
                       list(T="T11 People had",
                            TT=c("Cope with\ndifficult challenges",
                                 "Stopping\nsomething happening",
                                 "Improve the\nsituation"))
                     ))
)
#myLevs: Number of levels of Feeling: 3 or 5
Lev3 <- c("Negative","Neutral","Positive")
clev3 <- c(-1,0,1)
Lev5 <- c("Strongly negative","Negative","Neutral","Positive","Strongly positive")
clev5 <- c(-1,-0.5,0,0.5,1)

# Api key for the Yandex translation service (Chiara)
my_api_Yandex <- "trnsl.1.1.20160706T224335Z.fe93198853798e28.5a7788a7b9d5bc7a65ac5a0e94f85c9923a743d5"

